# Generated by Django 4.1.7 on 2023-03-14 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('street', models.TextField(blank=True, null=True, verbose_name='Colony / Street / Locality')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip code')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=255, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
    ]
